### PR TITLE
Fix: New simulator

### LINKED ISSUE #87: Fix the missing logic in the new simulator fixes
Complete and fix the simulator (branch `fix/new-simulator`):

* Remove useless flag `isRenderCalledByUser`. Check if the flag `isSimulationAnimated` is used at all and remove it if needed.
* Fix and remove TODOs in graph model, simulator engine, and views (which connects model and simulator)

### PR DESCRIPTION
**Pull request by AlexIchenskiy**
Closes #87 

This PR completes and fixes the simulator by refactoring code styling and logic and resolving remaining ToDo-s.

### CODE REVIEW

File: src/simulator/engine/d3-simulator-engine.ts [hunk 1]
```diff
@@ -184,19 +186,12 @@ export class D3SimulatorEngine extends Emitter<D3SimulatorEvents> {
...
-    */
-    // TODO(dlozic): Question2 (TLastre) I reverted this to the following and removed the (!) from settings:
-    this.settings = this.resetSettings();
+    this._settings = this.resetSettings();
     this.clearData();
   }
 
   getSettings(): ID3SimulatorEngineSettings {
-    return copyObject(this.settings);
+    return copyObject(this._settings);
```
Comment (tonilastre) [inline src/simulator/engine/d3-simulator-engine.ts:194]: All these calls of `copyObject` can be replaced with `structuredClone`

**Review by tonilastre — APPROVED** [review]
